name: Doorman
version: @VERSION@
description: Sends players messages when they join the server
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/Doorman
main: edgruberman.bukkit.doorman.Main
commands:
    'doorman:history':
        aliases: [doorman.history, doorman]
        description: View server declarations
        permission: doorman.history
        usage: '§f-> §7Usage: §b/<command> §3[§opage§3]'
    'doorman:show':
        aliases: [doorman.show, motd]
        description: Display current server declaration
        permission: doorman.show
        usage: '§f-> §7Usage: §b/<command> §3[§b§oindex§3]'
    'doorman:add':
        aliases: [doorman.add]
        description: Append a new server declaration
        permission: doorman.add
        usage: '§f-> §7Usage: §b/<command> §3§omessage'
    'doorman:edit':
        aliases: [doorman.edit]
        description: Replace existing server declaration
        permission: doorman.edit
        usage: '§f-> §7Usage: §b/<command> §3§omessage'
    'doorman:reload':
        description: Reload Doorman plugin
        permission: doorman.reload
        usage: '§f-> §7Usage: §b/<command>'
permissions:
    doorman.admin:
        description: Can use all features of plugin
        default: op
        children:
            doorman.user: true
            doorman.add: true
            doorman.edit: true
            doorman.reload: true
    doorman.user:
        description: Can use basic features of plugin
        default: true
        children:
            doorman.show: true
            doorman.history: true
    doorman.show:
        description: Can use show command
        default: false
    doorman.add:
        description: Can use add command
        default: false
    doorman.edit:
        description: Can use edit command
        default: false
    doorman.history:
        description: Can use history command
        default: false
    doorman.reload:
        description: Can use reload command
        default: false