name: Doorman
version: @VERSION@
description: Sends players messages when they join the game
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/Doorman
main: edgruberman.bukkit.doorman.Main
commands:
    'doorman:history':
        aliases: [doorman.history, doorman]
        description: View server join messages
        permission: doorman.history
        usage: /<command>[ <Page>]
    'doorman:show':
        aliases: [doorman.show, motd]
        description: Formats server join message
        permission: doorman.show
        usage: /<command>[ <Index>]
    'doorman:change':
        aliases: [doorman.change]
        description: Change the server join message
        permission: doorman.change
        usage: /<command> <Message>
    'doorman:reload':
        description: Reload Doorman plugin
        permission: doorman.reload
        usage: /<command>
permissions:
    doorman.admin:
        description: Can use all features of plugin
        default: op
        children:
            doorman.user: true
            doorman.change: true
            doorman.reload: true
    doorman.user:
        description: Can use basic features of plugin
        default: true
        children:
            doorman.show: true
            doorman.history: true
    doorman.show:
        description: Can use show command
        default: false
    doorman.change:
        description: Can use change command
        default: false
    doorman.history:
        description: Can use history command
        default: false
    doorman.reload:
        description: Can use reload command
        default: false